package com.hellengi.biolab.dto;

public record GenomeSettingsDto(
        RangedValueDto divisionThreshold,
        RangedValueDto divisionImpulse,
        RangedValueDto divisionAngle,
        RangedValueDto startNucleusDamage,
        RangedValueDto startCytosolDamage,
        RangedValueDto startCpDamage,
        RangedValueDto startMembraneDamage,
        RangedValueDto startLysosomeDamage,
        RangedValueDto startFlagellumDamage,
        RangedValueDto cytosolArea,
        RangedValueDto cytosolDensity,
        boolean bioluminescenceEnabled,
        RangedValueDto bioluminescence,
        RangedValueDto elasticity,
        boolean melaninEnabled,
        RangedValueDto melaninPercent,
        boolean chloroplastEnabled,
        RangedValueDto chloroplastAmount,
        RangedValueDto chlorophyll,
        RangedValueDto carotenoids,
        boolean lysosomeEnabled,
        RangedValueDto lysosomeAmount,
        RangedValueDto lysosomeEnzymeActivity,
        boolean flagellumEnabled,
        RangedValueDto flagellumCount,
        RangedValueDto flagellumLength,
        RangedValueDto flagellumMotorPower,
        RangedValueDto flagellumPairSpreadAngle,
        RangedValueDto flagellumSteeringAsymmetry,
        String code
) {
}
